package Day42_Exceptions;

public class ThrowsKeyword2 {

    public static void main(String[] args) throws ArithmeticException {

        System.out.println("Test started");

        System.out.println( 9 / 0 );// it continues giving error

        System.out.println("Test completed");


    }

}
